import { chromium } from 'playwright';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MIME = { '.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css' };
const server = http.createServer((req,res)=>{ let p=decodeURIComponent(req.url.split('?')[0]); if(p==='/')p='/index.html'; const fp=path.join(ROOT,p); if(!fs.existsSync(fp)||fs.statSync(fp).isDirectory()){res.writeHead(404);res.end('nf');return;} res.writeHead(200,{'Content-Type':MIME[path.extname(fp)]||'application/octet-stream'}); fs.createReadStream(fp).pipe(res); });
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const port = server.address().port;
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args:['--use-gl=angle','--use-angle=swiftshader','--ignore-gpu-blocklist','--no-sandbox'] });
const p = await b.newPage();
p.on('console', m => console.log('['+m.type()+']', m.text()));
p.on('pageerror', e => console.log('[pageerror]', e.message, e.stack?.split('\n')[1]||''));
p.on('requestfailed', r => console.log('[reqfail]', r.url(), r.failure()?.errorText));
await p.goto(`http://127.0.0.1:${port}/index.html`, { waitUntil:'load' });
await new Promise(r=>setTimeout(r,2500));
const st = await p.evaluate(()=>({ has: !!window.__SKYWARD__, keys: window.__SKYWARD__?Object.keys(window.__SKYWARD__):null }));
console.log('STATE', st);
await b.close(); server.close();
